//version 1.1

#ifndef GX_UI_RESOURCE
#define GX_UI_RESOURCE


#define GX_UI_UTL_BTN_BRWS_SCENE		200
#define GX_UI_UTL_BTN_EXPT_SCENE		201
#define GX_UI_UTL_BTN_EXPT_SKM			203
#define GX_UI_UTL_BTN_EXPT_STM			204
#define GX_UI_UTL_BTN_EXPT_ANI			205

#define GX_UI_UTL_CHK_EXPT_ELEMENTS		503
#define GX_UI_UTL_CHK_EXPT_UVS			504
#define GX_UI_UTL_CHK_EXPT_NORMALS		505
#define GX_UI_UTL_CHK_EXPT_TBPAIRS		506

#define GX_UI_UTL_EDT_SCENE_FILE		603
#define GX_UI_UTL_EDT_SKM_FILE			607
#define GX_UI_UTL_EDT_STM_FILE			608
#define GX_UI_UTL_EDT_ANI_FILE			609
#define GX_UI_UTL_EDT_ANI_START			610
#define GX_UI_UTL_EDT_ANI_LAST			611


#endif //GX_UI_RESOURCE
