//version 1.6

#include <GXEngine/GXOpenGL.h>
#include <GXCommon/GXLogger.h>


#define OPENGL_GET_PROC(p,n)					\
{												\
	n = ( p )wglGetProcAddress ( #n );			\
	if ( !n )									\
		GXLogA ( "#n не найдена\n" );			\
}


PFNWGLCREATECONTEXTATTRIBSARBPROC	wglCreateContextAttribsARB	= 0;
PFNWGLSWAPINTERVALEXTPROC			wglSwapIntervalEXT			= 0;
PFNGLGETSHADERIVPROC				glGetShaderiv				= 0;
PFNGLGETPROGRAMIVPROC				glGetProgramiv				= 0;
PFNGLGETSHADERINFOLOGPROC			glGetShaderInfoLog			= 0;
PFNGLGETPROGRAMINFOLOGPROC			glGetProgramInfoLog			= 0;
PFNGLGENVERTEXARRAYSPROC			glGenVertexArrays			= 0;
PFNGLBINDVERTEXARRAYPROC			glBindVertexArray			= 0;
PFNGLGENBUFFERSPROC					glGenBuffers				= 0;
PFNGLBINDBUFFERPROC					glBindBuffer				= 0;
PFNGLBUFFERDATAPROC					glBufferData				= 0;
PFNGLCREATEPROGRAMPROC				glCreateProgram				= 0;
PFNGLCREATESHADERPROC				glCreateShader				= 0;
PFNGLSHADERSOURCEPROC				glShaderSource				= 0;
PFNGLCOMPILESHADERPROC				glCompileShader				= 0;
PFNGLATTACHSHADERPROC				glAttachShader				= 0;
PFNGLLINKPROGRAMPROC				glLinkProgram				= 0;
PFNGLUSEPROGRAMPROC					glUseProgram				= 0;
PFNGLVALIDATEPROGRAMPROC			glValidateProgram			= 0;
PFNGLGETATTRIBLOCATIONPROC			glGetAttribLocation			= 0;
PFNGLVERTEXATTRIBPOINTERPROC		glVertexAttribPointer		= 0;
PFNGLVERTEXATTRIB4NUBPROC			glVertexAttrib4Nub			= 0;
PFNGLENABLEVERTEXATTRIBARRAYPROC	glEnableVertexAttribArray	= 0;
PFNGLGETUNIFORMLOCATIONPROC			glGetUniformLocation		= 0;
PFNGLDELETESHADERPROC				glDeleteShader				= 0;
PFNGLDELETEPROGRAMPROC				glDeleteProgram				= 0;
PFNGLUNIFORM1IPROC					glUniform1i					= 0;
PFNGLUNIFORM1FPROC					glUniform1f					= 0;
PFNGLUNIFORM1FVPROC					glUniform1fv				= 0;
PFNGLUNIFORM2FVPROC					glUniform2fv				= 0;
PFNGLUNIFORM3FVPROC					glUniform3fv				= 0;
PFNGLUNIFORM4FPROC					glUniform4f					= 0;
PFNGLUNIFORM4FVPROC					glUniform4fv				= 0;
PFNGLUNIFORMMATRIX3FVPROC			glUniformMatrix3fv			= 0;
PFNGLUNIFORMMATRIX4FVPROC			glUniformMatrix4fv			= 0;
PFNGLDELETEVERTEXARRAYSPROC			glDeleteVertexArrays		= 0;
PFNGLDELETEBUFFERSPROC				glDeleteBuffers				= 0;
PFNGLGENFRAMEBUFFERSPROC			glGenFramebuffers			= 0;
PFNGLBINDFRAMEBUFFERPROC			glBindFramebuffer			= 0;
PFNGLFRAMEBUFFERTEXTURE2DPROC		glFramebufferTexture2D		= 0;
PFNGLDELETEFRAMEBUFFERSPROC			glDeleteFramebuffers		= 0;
PFNGLACTIVETEXTUREPROC				glActiveTexture				= 0;
PFNGLBINDRENDERBUFFERPROC			glBindRenderbuffer			= 0;
PFNGLGENRENDERBUFFERSPROC			glGenRenderbuffers			= 0;
PFNGLRENDERBUFFERSTORAGEPROC		glRenderbufferStorage		= 0;
PFNGLFRAMEBUFFERRENDERBUFFERPROC	glFramebufferRenderbuffer	= 0;
PFNGLCHECKFRAMEBUFFERSTATUSPROC		glCheckFramebufferStatus	= 0;
PFNGLDELETERENDERBUFFERSPROC		glDeleteRenderbuffers		= 0;
PFNGLDRAWBUFFERSPROC				glDrawBuffers				= 0;
PFNGLDISABLEVERTEXATTRIBARRAYPROC	glDisableVertexAttribArray	= 0;
PFNGLDRAWRANGEELEMENTSPROC			glDrawRangeElements			= 0;
PFNGLBLENDEQUATIONPROC				glBlendEquation				= 0;
PFNGLBLENDFUNCSEPARATEPROC			glBlendFuncSeparate			= 0;
PFNGLGENERATEMIPMAPPROC				glGenerateMipmap			= 0;
PFNGLSTENCILOPSEPARATEPROC			glStencilOpSeparate			= 0;
PFNGLTRANSFORMFEEDBACKVARYINGSPROC	glTransformFeedbackVaryings	= 0;
PFNGLBINDBUFFERBASEPROC				glBindBufferBase			= 0;
PFNGLBINDBUFFERRANGEPROC			glBindBufferRange			= 0;
PFNGLBEGINTRANSFORMFEEDBACKPROC		glBeginTransformFeedback	= 0;
PFNGLENDTRANSFORMFEEDBACKPROC		glEndTransformFeedback		= 0;
PFNGLTEXIMAGE3DPROC					glTexImage3D				= 0;
PFNGLFRAMEBUFFERTEXTUREPROC			glFramebufferTexture		= 0;
PFNGLGENSAMPLERSPROC				glGenSamplers				= 0;
PFNGLDELETESAMPLERSPROC				glDeleteSamplers			= 0;
PFNGLBINDSAMPLERPROC				glBindSampler				= 0;
PFNGLSAMPLERPARAMETERIPROC			glSamplerParameteri			= 0;
PFNGLSAMPLERPARAMETERFPROC			glSamplerParameterf			= 0;


GXVoid GXCALL GXOpenGLInit ()
{
	wglCreateContextAttribsARB = reinterpret_cast<PFNWGLCREATECONTEXTATTRIBSARBPROC> ( wglGetProcAddress ( "wglCreateContextAttribsARB" ) );

	OPENGL_GET_PROC ( PFNWGLSWAPINTERVALEXTPROC,			wglSwapIntervalEXT			);
	OPENGL_GET_PROC ( PFNGLGETSHADERIVPROC,					glGetShaderiv				);
	OPENGL_GET_PROC ( PFNGLGETPROGRAMIVPROC,				glGetProgramiv				);
	OPENGL_GET_PROC ( PFNGLGETSHADERINFOLOGPROC,			glGetShaderInfoLog			);
	OPENGL_GET_PROC ( PFNGLGETPROGRAMINFOLOGPROC,			glGetProgramInfoLog			);
	OPENGL_GET_PROC ( PFNGLGENVERTEXARRAYSPROC,				glGenVertexArrays			);
	OPENGL_GET_PROC ( PFNGLBINDVERTEXARRAYPROC,				glBindVertexArray			);
	OPENGL_GET_PROC ( PFNGLGENBUFFERSPROC,					glGenBuffers				);
	OPENGL_GET_PROC ( PFNGLBINDBUFFERPROC,					glBindBuffer				);
	OPENGL_GET_PROC ( PFNGLBUFFERDATAPROC,					glBufferData				);
	OPENGL_GET_PROC ( PFNGLCREATEPROGRAMPROC,				glCreateProgram				);
	OPENGL_GET_PROC ( PFNGLCREATESHADERPROC,				glCreateShader				);
	OPENGL_GET_PROC ( PFNGLSHADERSOURCEPROC,				glShaderSource				);
	OPENGL_GET_PROC ( PFNGLCOMPILESHADERPROC,				glCompileShader				);
	OPENGL_GET_PROC ( PFNGLATTACHSHADERPROC,				glAttachShader				);
	OPENGL_GET_PROC ( PFNGLLINKPROGRAMPROC,					glLinkProgram				);
	OPENGL_GET_PROC ( PFNGLUSEPROGRAMPROC,					glUseProgram				);
	OPENGL_GET_PROC ( PFNGLVALIDATEPROGRAMPROC,				glValidateProgram			);
	OPENGL_GET_PROC ( PFNGLGETATTRIBLOCATIONPROC,			glGetAttribLocation			);
	OPENGL_GET_PROC ( PFNGLVERTEXATTRIBPOINTERPROC,			glVertexAttribPointer		);
	OPENGL_GET_PROC ( PFNGLVERTEXATTRIB4NUBPROC,			glVertexAttrib4Nub			);
	OPENGL_GET_PROC ( PFNGLENABLEVERTEXATTRIBARRAYPROC,		glEnableVertexAttribArray	);
	OPENGL_GET_PROC ( PFNGLGETUNIFORMLOCATIONPROC,			glGetUniformLocation		);
	OPENGL_GET_PROC ( PFNGLDELETESHADERPROC,				glDeleteShader				);
	OPENGL_GET_PROC ( PFNGLDELETEPROGRAMPROC,				glDeleteProgram				);
	OPENGL_GET_PROC ( PFNGLUNIFORM1IPROC,					glUniform1i					);
	OPENGL_GET_PROC ( PFNGLUNIFORM1FPROC,					glUniform1f					);
	OPENGL_GET_PROC ( PFNGLUNIFORM1FVPROC,					glUniform1fv				);
	OPENGL_GET_PROC ( PFNGLUNIFORM2FVPROC,					glUniform2fv				);
	OPENGL_GET_PROC ( PFNGLUNIFORM3FVPROC,					glUniform3fv				);
	OPENGL_GET_PROC ( PFNGLUNIFORM4FPROC,					glUniform4f					);
	OPENGL_GET_PROC ( PFNGLUNIFORM4FVPROC,					glUniform4fv				);
	OPENGL_GET_PROC ( PFNGLUNIFORMMATRIX3FVPROC,			glUniformMatrix3fv			);
	OPENGL_GET_PROC ( PFNGLUNIFORMMATRIX4FVPROC,			glUniformMatrix4fv			);
	OPENGL_GET_PROC ( PFNGLDELETEVERTEXARRAYSPROC,			glDeleteVertexArrays		);
	OPENGL_GET_PROC ( PFNGLDELETEBUFFERSPROC,				glDeleteBuffers				);
	OPENGL_GET_PROC ( PFNGLGENFRAMEBUFFERSPROC,				glGenFramebuffers			);
	OPENGL_GET_PROC ( PFNGLBINDFRAMEBUFFERPROC,				glBindFramebuffer			);
	OPENGL_GET_PROC ( PFNGLFRAMEBUFFERTEXTURE2DPROC,		glFramebufferTexture2D		);
	OPENGL_GET_PROC ( PFNGLDELETEFRAMEBUFFERSPROC,			glDeleteFramebuffers		);
	OPENGL_GET_PROC ( PFNGLACTIVETEXTUREPROC,				glActiveTexture				);
	OPENGL_GET_PROC ( PFNGLBINDRENDERBUFFERPROC,			glBindRenderbuffer			);
	OPENGL_GET_PROC ( PFNGLGENRENDERBUFFERSPROC,			glGenRenderbuffers			);
	OPENGL_GET_PROC ( PFNGLRENDERBUFFERSTORAGEPROC,			glRenderbufferStorage		);
	OPENGL_GET_PROC ( PFNGLFRAMEBUFFERRENDERBUFFERPROC,		glFramebufferRenderbuffer   );
	OPENGL_GET_PROC ( PFNGLCHECKFRAMEBUFFERSTATUSPROC,		glCheckFramebufferStatus	);
	OPENGL_GET_PROC ( PFNGLDELETERENDERBUFFERSPROC,			glDeleteRenderbuffers		);
	OPENGL_GET_PROC ( PFNGLDRAWBUFFERSPROC,					glDrawBuffers				);
	OPENGL_GET_PROC ( PFNGLDISABLEVERTEXATTRIBARRAYPROC,	glDisableVertexAttribArray	);
	OPENGL_GET_PROC ( PFNGLDRAWRANGEELEMENTSPROC,			glDrawRangeElements			);
	OPENGL_GET_PROC ( PFNGLBLENDEQUATIONPROC,				glBlendEquation				);
	OPENGL_GET_PROC ( PFNGLBLENDFUNCSEPARATEPROC,			glBlendFuncSeparate			);
	OPENGL_GET_PROC ( PFNGLGENERATEMIPMAPPROC,				glGenerateMipmap			);
	OPENGL_GET_PROC ( PFNGLSTENCILOPSEPARATEPROC,			glStencilOpSeparate			);
	OPENGL_GET_PROC ( PFNGLTRANSFORMFEEDBACKVARYINGSPROC,	glTransformFeedbackVaryings	);
	OPENGL_GET_PROC ( PFNGLBINDBUFFERBASEPROC,				glBindBufferBase			);
	OPENGL_GET_PROC ( PFNGLBINDBUFFERRANGEPROC,				glBindBufferRange			);
	OPENGL_GET_PROC ( PFNGLBEGINTRANSFORMFEEDBACKPROC,		glBeginTransformFeedback	);
	OPENGL_GET_PROC ( PFNGLENDTRANSFORMFEEDBACKPROC,		glEndTransformFeedback		);
	OPENGL_GET_PROC ( PFNGLTEXIMAGE3DPROC,					glTexImage3D				);
	OPENGL_GET_PROC ( PFNGLFRAMEBUFFERTEXTUREPROC,			glFramebufferTexture		);
	OPENGL_GET_PROC ( PFNGLGENSAMPLERSPROC,					glGenSamplers				);
	OPENGL_GET_PROC ( PFNGLDELETESAMPLERSPROC,				glDeleteSamplers			);
	OPENGL_GET_PROC ( PFNGLBINDSAMPLERPROC,					glBindSampler				);
	OPENGL_GET_PROC ( PFNGLSAMPLERPARAMETERIPROC,			glSamplerParameteri			);
	OPENGL_GET_PROC ( PFNGLSAMPLERPARAMETERFPROC,			glSamplerParameterf			);
}

GXVoid GXCALL GXCheckOpenGLError ()
{
	GLenum error;

	if ( ( error = glGetError () ) != GL_NO_ERROR )
		GXLogA ( "OpenGL::Error 0x%08X\n", (GXUInt)error );
}
